# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ubuntu/Projects/Port/ui/login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(441, 139)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.editUsername = QtWidgets.QLineEdit(Form)
        self.editUsername.setObjectName("editUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editUsername)
        self.editPassword = QtWidgets.QLineEdit(Form)
        self.editPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPassword.setObjectName("editPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editPassword)
        self.buttonSubmit = QtWidgets.QPushButton(Form)
        self.buttonSubmit.setObjectName("buttonSubmit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttonSubmit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Port - Login"))
        self.label.setText(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "Username"))
        self.label_3.setText(_translate("Form", "Password"))
        self.buttonSubmit.setText(_translate("Form", "Login"))
